server:
  port: 8888
spring:
  application:
    name: apollo-config-server
  cloud:
    config:
      server:
        git:
          uri: ${URI_REPOSITORIO}
          search-paths: 'greeting-service*'
          username: ${USUARIO_GITHUB}
          password: ${TOKEN}
        default-label: main