server:
  port: 8000
spring:
  application:
    name: cambio-service
  datasource:
    url: jdbc:mysql://localhost:3306/cambio_service?allowPublicKeyRetrieval=true&useSSL=false
    username: ${usr}
    password: ${pwd}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  flyway:
    url: jdbc:mysql://localhost:3306/
    schemas: cambio_service
    user: ${usr}
    password: ${pwd}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka