server:
  port: 8100
spring:
  application:
    name: book-service
  datasource:
    url: jdbc:mysql://localhost:3306/book_service?allowPublicKeyRetrieval=true&useSSL=false
    username: ${usr}
    password: ${pwd}
  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      fail-on-empty-beans: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  flyway:
    url: jdbc:mysql://localhost:3306/
    schemas: book_service
    user: ${usr}
    password: ${pwd}